### ISSUE TITLE
Contract call?

### ISSUE THREAD

**Issue by EHSchmitt4395** [smye/1inch-swap#1]
Hey ! First off thanks so much for making this available --- this is the only example ive been able to find and its the furthest ive ever gotten into integrating 1inch into my contract. 

I'm presently trying to call this contract from another contract --- but nothing seems to happen.  

I tried removing the `is Ownable` and the `onlyOwner`. My other contract appropriately defines 
```
import "./interfaces/SwapProxy.sol";
....
    address internal constant SWAP_PROXY = 0xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx;
    SwapProxy public swappproxy;

    constructor() {
        swappproxy = SwapProxy(SWAP_PROXY);
    }
```
and i attempt to `swappproxy.swap(data); `    

Nothing happens. I've been debugging with tenderly and it doesnt seem to call the swap proxy contract at all.  Curious if you know an obvious answer here. Or if you were aware of anything else i might need to make this work out.  
"[ERROR]":"execution reverted"
```
"state":{
"swapproxy":"0x0000000000000000000000000000000000000000"
"_owner":"0xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
}
```

Thanks so much !! really hope you can help

**Comment by smye** [comment]
Hey!

No problem, glad it somewhat helpful 😄

Since I don't have the full code, going to have a wild guess and say it's because you're missing an argument in swap() and thus isn't finding any function. 

```solidity
function swap(uint minOut, bytes calldata _data) external onlyOwner {
```

Feel free to open a repo with your code or find me in the 1inch Discord, and will be happy to look into it further!

**Comment by EHSchmitt4395** [comment]
Found you on Discord and sent you a message :D !!! Thanks so much for the reply!
