### ISSUE TITLE
Example for 1inchV4 router swap

### ISSUE THREAD

**Issue by RickVM** [smye/1inch-swap#2]
Hi There,

Nice repo. Could you tell me how you figured out how to decode and encode the data used in the swap?   
I'm trying to implement a proxySwap for the v4 router in a similar manner, the calldata is also generated through the 1inch apoi `https://etherscan.io/address/0x1111111254fb6c44bac0bed2854e76f90643097d`
 
I have attached 2 comments in the code to clarify my question and situation

```solidity
  function swap(uint minOut, bytes calldata _data) external onlyOwner {
        (address _c, SwapDescription memory desc, bytes memory _d) = abi.decode(_data[4:], (address, SwapDescription, bytes));
        // How did you know it is _data[4:]? Perhaps this is different for V4 router

        IERC20(desc.srcToken).transferFrom(msg.sender, address(this), desc.amount);
        IERC20(desc.srcToken).approve(AGGREGATION_ROUTER_V4, desc.amount);

        (bool succ, bytes memory _data) = address(AGGREGATION_ROUTER_V4).call(_data);
        if (succ) {
            // We fail on the next line, _data is 0x so it fails
            (uint returnAmount, uint gasLeft) = abi.decode(_data, (uint, uint));
            require(returnAmount >= minOut);
        } else {
            revert();
        }
    }
}
```

**Comment by RickVM** [comment]
Never mind, I messed up some things myself. This example also works for v4!

**Comment by smye** [comment]
> Never mind, I messed up some things myself. This example also works for v4!

Hey!

Glad you got it working 🙂

Will just leave what I think are the answers to your question below just in case anyone else finds them in the same situation:

1) `_data[4:]` is for removing the function selector from the calldata returned by the 1inch API. The function selector determines what function is called
2) V4 adds an extra return value `spentAmount` on the swap function:
    ```solidity
    function swap(
            IAggregationExecutor caller,
            SwapDescription calldata desc,
            bytes calldata data
        )
            external
            payable
            returns (
                uint256 returnAmount,
                uint256 spentAmount,
                uint256 gasLeft
            )
        {
    ```
    So replace

   ```solidity
    (uint returnAmount, uint gasLeft) = abi.decode(_data, (uint, uint));
    ````
    with
    ```solidity
    (uint returnAmount, uint spentAmount, uint gasLeft) = abi.decode(_data, (uint, uint, uint));
    ````

**Comment by RickVM** [comment]
> 2. V4 adds an extra return value `spentAmount` on the swap function:
>    ```solidity
>    function swap(
>            IAggregationExecutor caller,
>            SwapDescription calldata desc,
>            bytes calldata data
>        )
>            external
>            payable
>            returns (
>                uint256 returnAmount,
>                uint256 spentAmount,
>                uint256 gasLeft
>            )
>        {
>    ```

This is true for Ethereum but it seems 1inch has not updated this on Polygon and binance smart chain.   
There, the old return parameters are still used

**Comment by bmarcot** [comment]
> > Never mind, I messed up some things myself. This example also works for v4!
> 
> Hey!
> 
> Glad you got it working 🙂
> 
> Will just leave what I think are the answers to your question below just in case anyone else finds them in the same situation:
> 
> 1. `_data[4:]` is for removing the function selector from the calldata returned by the 1inch API. The function selector determines what function is called
> 2. V4 adds an extra return value `spentAmount` on the swap function:
>    ```solidity
>    function swap(
>            IAggregationExecutor caller,
>            SwapDescription calldata desc,
>            bytes calldata data
>        )
>            external
>            payable
>            returns (
>                uint256 returnAmount,
>                uint256 spentAmount,
>                uint256 gasLeft
>            )
>        {
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    So replace
>    ```solidity
>     (uint returnAmount, uint gasLeft) = abi.decode(_data, (uint, uint));
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    with
>    ```solidity
>    (uint returnAmount, uint spentAmount, uint gasLeft) = abi.decode(_data, (uint, uint, uint));
>    ```

Hey @smye, you assume the return type for `swap()` on V4 with extra `spentAmount` at positional arg. number 2. But 1inch docs for V4 says prototype is still the old V3 [prototype](https://docs.1inch.io/docs/aggregation-protocol/smart-contract/AggregationRouterV4#swap).  Can you confirm which is correct?

**Comment by bmarcot** [comment]
> > > Never mind, I messed up some things myself. This example also works for v4!
> > 
> > 
> > Hey!
> > Glad you got it working 🙂
> > Will just leave what I think are the answers to your question below just in case anyone else finds them in the same situation:
> > 
> > 1. `_data[4:]` is for removing the function selector from the calldata returned by the 1inch API. The function selector determines what function is called
> > 2. V4 adds an extra return value `spentAmount` on the swap function:
> >    ```solidity
> >    function swap(
> >            IAggregationExecutor caller,
> >            SwapDescription calldata desc,
> >            bytes calldata data
> >        )
> >            external
> >            payable
> >            returns (
> >                uint256 returnAmount,
> >                uint256 spentAmount,
> >                uint256 gasLeft
> >            )
> >        {
> >    ```
> >    
> >    
> >        
> >          
> >        
> >    
> >          
> >        
> >    
> >        
> >      
> >    So replace
> >    ```solidity
> >     (uint returnAmount, uint gasLeft) = abi.decode(_data, (uint, uint));
> >    ```
> >    
> >    
> >        
> >          
> >        
> >    
> >          
> >        
> >    
> >        
> >      
> >    with
> >    ```solidity
> >    (uint returnAmount, uint spentAmount, uint gasLeft) = abi.decode(_data, (uint, uint, uint));
> >    ```
> 
> Hey @smye, you assume the return type for `swap()` on V4 with extra `spentAmount` at positional arg. number 2. But 1inch docs for V4 says prototype is still the old V3 [prototype](https://docs.1inch.io/docs/aggregation-protocol/smart-contract/AggregationRouterV4#swap). Can you confirm which is correct?

Nevermind, found it -- https://etherscan.io/address/0x1111111254fb6c44bac0bed2854e76f90643097d#code#L2319
Doc hasn't been updated.
